#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#xrandr --output eDP --primary &
xrandr --output eDP --mode 1920x1080 --rate 60 --primary &

bspc monitor eDP -d 1 2 3 4 5 6 7 8

bspc config border_width			2
bspc config window_gap				10
bspc config split_ratio				0.5
bspc config pointer_motion_interval 		0

bspc config focused_border_color	"#cba6f7"
bspc config normal_border_color		"#45475a"
bspc config active_border_color		"#a6e3a1"
bspc config presel_feedback_color	"#89b4fa"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

# remove all rules first
#bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
declare -a code=(jetbrains-idea-ce kitty-now)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^1' follow=on focus=on; done

## 2 > web (always open web browser on workspace-2)
bspc rule -a Google-chrome desktop='^2' follow=on focus=on
bspc rule -a firefoxdeveloperedition desktop='^2' follow=on focus=on

## 3 > files (always open file manager on workspace-3)
declare -a code=(Geany Code)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^3' follow=on focus=on; done

## 4 > code (always open editors on workspace-4)
declare -a files=(Nemo)
for i in ${files[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

## 5 > office and docs (always open office/doc apps on workspace-5)
declare -a office=(Gucharmap Atril Zathura \
libreoffice-writer LibreOffice libreoffice-calc libreoffice-impress \
libreoffice-startcenter libreoffice libreoffice-* Soffice *:libreofficedev *:soffice)
for i in ${office[@]}; do
   bspc rule -a $i desktop='^5' follow=on focus=on; done
   
bspc rule -a 'ONLYOFFICE Desktop Editors' desktop='^5' follow=on focus=on

## 6 > communication (always open communication apps on workspace-6)
declare -a comm=(thunderbird TelegramDesktop Transmission-gtk retroarch)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

## 7 > media (always open media apps on workspace-7)
declare -a media=(Audacity cantata MPlayer Inkscape Gimp-2.10 mpv)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' follow=on focus=on; done

bspc rule -a 'YouTube Music' desktop='^7' follow=on focus=on

## 8 > system (always open system apps on workspace-8)
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Blueman-manager SimpleScreenRecorder \
Pavucontrol Xfce4-power-manager-settings Nitrogen Nm-connection-editor)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

## Always Floating Apps
declare -a floating=(kitty-float MEGAsync mpv \
Viewnior Gthumb feh Qalculate-gtk Java dolphin-emu)

for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

## Always Tiled Apps
declare -a tileding=(Zathura)

for i in ${tileding[@]}; do
   bspc rule -a $i state=tiled follow=on focus=on; done

bspc rule -a conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall dunst &
killall redshift-gtk &
# killall xfce4-power-manager &

# Dunst
dunst -config ~/.config/dunst/dunstrc &

# Compositor
# picom -b --experimental-backends &
picom -b --config ~/.config/picom/picom.conf &

# Portapapeles
clipmenud &

# Java App
wmname LG3D &

# polkit agent
if [[ ! `pidof polkit-gnome-authentication-agent-1` ]]; then
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Enable power management
xss-lock --transfer-sleep-lock -- /home/josue/.config/lock.sh --nofork &
# xfce4-power-manager &

# Gestos touchpad
libinput-gestures-setup start &

# Fix cursor
xsetroot -cursor_name left_ptr &

# Keyboard layout
setxkbmap -option grp:rctrl_rshift_toggle us,latam &

# Num Lock
numlockx &

# Restore wallpaper
# nitrogen --restore &
#ramdomwall /home/josue/Imágenes/Nord/custom 300 &
feh --bg-fill "/home/josue/Imágenes/Catppuccin/cat_lofi_cafe.jpg"

# Start mpd
exec mpd &

# Polybar
~/.config/polybar/launch.sh &

# tray
# Exclusive apps
if [[ ! $(pidof stalonetray) ]]; then
	stalonetray &
	sleep 0.5
	xdo hide -N stalonetray
	touch "/tmp/syshide.lock"
fi

# start app
megasync &

#blueman-applet &

# ~/.config/conky/Alterf/start.sh &

redshift-gtk &
