splash = false
preload = ~/Imágenes/Catppuccin/cat_lofi_cafe.jpg
wallpaper = eDP-1,~/Imágenes/Catppuccin/cat_lofi_cafe.jpg
preload = ~/Imágenes/Catppuccin/forest_dark_winter.jpg
wallpaper = HDMI-A-1,~/Imágenes/Catppuccin/forest_dark_winter.jpg
